pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main' ,
                url: 'https://github.com/sunilkrishna49/estore-admin-dashboard.git'
                 
            }
        }
        stage('Build') {
            steps {
                sh ',/mvnw clean package'
            }
        }
        stage('Dockerize') {
            steps {
                sh 'docker build -t estore-backend .'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 9094:9094 estore-backend'
            }
        }
    }
}
